name: gitleaks
on: [pull_request]
jobs:
 gitleaks_scan:
    name: Gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: adtyarai/gitleaks-action1@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          github_repository: ${{ github.repository }}
          latest_commit: ${{ github.event.after }}
