name: gitleaks
on: [pull_request]
jobs:
 gitleaks_scan:
    name: Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Branch Name
        run: |
          echo "Branch Name: ${{ github.head_ref }} ${{ github.repository }} ${{ github.event.before }} ${{ github.event.after }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set execute permission
        run: chmod +x ./gitleaks.sh
    

      - name: Run Gitleaks Scan
        run: ./gitleaks.sh "${{ secrets.GITHUB_TOKEN }}" "${{ github.event.pull_request.number}}" "${{ github.event.after }}"
